# Generated by Django 3.2 on 2021-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210506_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_num',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Enter Your Phone Number'),
        ),
    ]
