# Generated by Django 3.2 on 2021-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_patient_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drop_location',
            field=models.CharField(max_length=200, verbose_name='Enter Drop Location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickup_location',
            field=models.CharField(max_length=200, verbose_name='Enter Pickup Location'),
        ),
    ]
