# Generated by Django 3.2 on 2021-05-06 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210506_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
