# Generated by Django 3.2 on 2021-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_patient_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='caretaker_name',
            field=models.CharField(default='', max_length=50, verbose_name='Patient Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='drop_location',
            field=models.CharField(max_length=70, verbose_name='Enter Drop Location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickup_location',
            field=models.CharField(max_length=70, verbose_name='Enter Pickup Location'),
        ),
    ]
