# Generated by Django 3.2 on 2021-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210507_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caretaker_name',
            field=models.CharField(max_length=50, verbose_name='Caretaker Name'),
        ),
    ]
