# Generated by Django 3.2 on 2021-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210507_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Patient Name')),
                ('caretaker_name', models.CharField(max_length=50, verbose_name='Caretaker Name')),
                ('contact_num', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Enter Your Phone Number')),
                ('pickup_location', models.CharField(max_length=70, verbose_name='Enter Pickup Location')),
                ('drop_location', models.CharField(max_length=70, verbose_name='Enter Drop Location')),
                ('time_created', models.DateTimeField()),
            ],
        ),
    ]
